export const eras = [
  {
    id: 1,
    number: '01',
    title: 'Transformer Era',
    years: '2017',
    breakthrough: 'Transformers Introduced',
    paper: '"Attention Is All You Need" (2017)',
    color: 'blue',
    accent: '#3b82f6',
    bg: 'from-blue-950/80 to-blue-900/40',
    border: 'border-blue-500/40',
    badge: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    dot: 'bg-blue-500',
    icon: '🔄',
    keyInnovations: ['Attention Mechanism', 'Self-Attention', 'Parallel Processing', 'Representation Learning'],
    keyResearchers: ['Ashish Vaswani', 'Jakob Uszkoreit', 'Noam Shazeer', 'Aidan Gomez', 'Illia Polosukhin'],
    leadingCompanies: ['Google Research'],
    gap: 'Transformers enabled language understanding but lacked generation autonomy, reasoning capability, and foundation model scaling.',
    leadsTo: 'Generative AI',
  },
  {
    id: 2,
    number: '02',
    title: 'Generative AI Era',
    years: '2018 – 2023',
    breakthrough: 'Foundation Models + Large-Scale Generation',
    color: 'violet',
    accent: '#8b5cf6',
    bg: 'from-violet-950/80 to-violet-900/40',
    border: 'border-violet-500/40',
    badge: 'bg-violet-500/20 text-violet-300 border-violet-500/30',
    dot: 'bg-violet-500',
    icon: '✨',
    milestones: [
      { year: '2018', item: 'GPT-1' },
      { year: '2019', item: 'GPT-2' },
      { year: '2020', item: 'GPT-3' },
      { year: '2022', item: 'ChatGPT' },
      { year: '2023', item: 'GPT-4' },
    ],
    keyCapabilities: ['Text Generation', 'Image Generation', 'Code Generation', 'Conversational AI'],
    leadingCompanies: ['OpenAI', 'Anthropic', 'Meta AI', 'Google DeepMind'],
    gap: 'Lacked planning, reasoning, autonomy, multi-step experience, and the ability to execute real-world actions.',
    leadsTo: 'Agentic AI',
  },
  {
    id: 3,
    number: '03',
    title: 'Agentic AI Era',
    years: '2023 – 2025',
    breakthrough: 'Reason + Plan + Act',
    color: 'amber',
    accent: '#f59e0b',
    bg: 'from-amber-950/80 to-amber-900/40',
    border: 'border-amber-500/40',
    badge: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    dot: 'bg-amber-500',
    icon: '🤖',
    coreConcepts: ['ReAct', 'Chain-of-Thought', 'Reflection', 'Tool Use', 'Multi-Agent Systems'],
    leadingCompanies: ['LangChain', 'CrewAI', 'Microsoft AutoGen', 'OpenAI'],
    gap: 'Fragmented actions, inconsistent behavior, orchestration gaps, lack of enterprise governance, and cost explosion.',
    leadsTo: 'Cognitive AI',
  },
  {
    id: 4,
    number: '04',
    title: 'Cognitive AI / Compound AI',
    years: '2024 – 2026',
    breakthrough: 'Orchestration',
    color: 'pink',
    accent: '#ec4899',
    bg: 'from-pink-950/80 to-pink-900/40',
    border: 'border-pink-500/40',
    badge: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
    dot: 'bg-pink-500',
    icon: '🧠',
    keyInnovations: ['Cognitive Architectures', 'Reflection Systems', 'LLM Judges', 'Workflow Orchestration', 'MCP Ecosystem'],
    leadingCompanies: ['LangGraph', 'Anthropic', 'LlamaIndex'],
    gap: 'Still missing persistent enterprise cognition, deep cross-system workflows, enterprise-scale memory management, and governed runtime systems.',
    leadsTo: 'AI Digital Workers',
  },
  {
    id: 5,
    number: '05',
    title: 'AI Digital Workers Era',
    years: '2025 – 2027',
    breakthrough: 'AI as a Digital Workforce',
    color: 'teal',
    accent: '#14b8a6',
    bg: 'from-teal-950/80 to-teal-900/40',
    border: 'border-teal-500/40',
    badge: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
    dot: 'bg-teal-500',
    icon: '👥',
    keyInnovations: ['Workforce Orchestration', 'Role Specialization', 'Digital Labor', 'Worker Governance'],
    shift: 'Task execution → AI as Digital Workforce',
    leadingCompanies: ['CrewAI', 'Microsoft', 'Salesforce'],
    gap: 'Digital workers needed dynamic, executable, intelligent, and adaptive synthetic workflows to operate at enterprise scale.',
    leadsTo: 'Generative Execution Engines',
  },
  {
    id: 6,
    number: '06',
    title: 'Generative Execution Engines',
    years: '2025 – 2028',
    breakthrough: 'AI Generates Executable Workflows',
    abbrev: 'GEE',
    color: 'emerald',
    accent: '#10b981',
    bg: 'from-emerald-950/80 to-emerald-900/40',
    border: 'border-emerald-500/40',
    badge: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    dot: 'bg-emerald-500',
    icon: '⚙️',
    capabilities: ['DAG Generation', 'Temporal Workflows', 'Composable Services', 'Agentic Kafka'],
    keyTechnologies: ['Agentiq', 'Kafka', 'Promptfoo'],
    leadingCompanies: ['CrewAI', 'Microsoft', 'Salesforce'],
    gap: 'Need to unify cognitive governance, align enterprise operations, and govern enterprise AI at scale.',
    leadsTo: 'AI Enterprise Operating Systems',
  },
  {
    id: 7,
    number: '07',
    title: 'AI Enterprise Operating Systems',
    years: '2026 – 2030+',
    breakthrough: 'AI as the Enterprise Runtime',
    abbrev: 'AI-EOS',
    color: 'indigo',
    accent: '#6366f1',
    bg: 'from-indigo-950/80 to-indigo-900/40',
    border: 'border-indigo-500/40',
    badge: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    dot: 'bg-indigo-500',
    icon: '🏢',
    keyConcepts: ['AI Orchestration', 'Cognitive Dimension', 'AI Memory Factory', 'Enterprise Governance'],
    function: 'Purpose Bus, Orchestrate, Govern and Evolve the Entire Enterprise using AI',
    leadingCompanies: ['OpenAI', 'Anthropic', 'NVIDIA', 'Google Cloud'],
    gap: null,
    leadsTo: 'Next Frontier',
  },
]

export const timelineItems = [
  { year: '2017', era: 'Transformer Era', color: '#3b82f6' },
  { year: '2018–2023', era: 'Generative AI', color: '#8b5cf6' },
  { year: '2023–2025', era: 'Agentic AI', color: '#f59e0b' },
  { year: '2024–2026', era: 'Cognitive AI', color: '#ec4899' },
  { year: '2025–2027', era: 'AI Digital Workers', color: '#14b8a6' },
  { year: '2025–2028', era: 'GEE', color: '#10b981' },
  { year: '2026–2030+', era: 'AI-EOS', color: '#6366f1' },
]

export const keyDrivers = [
  { label: 'Model Scale', icon: '📈' },
  { label: 'Reasoning Depth', icon: '🧩' },
  { label: 'Agentic Autonomy', icon: '🤖' },
  { label: 'Enterprise Complexity', icon: '🏗️' },
]
