export const learnContent = {
  1: {
    path: [
      {
        step: 1, level: 'Beginner', time: '2 hrs',
        title: 'Understand Attention Intuitively',
        description: 'Start with Jay Alammar\'s illustrated walkthrough — no math required. Grasp why attention outperforms RNNs before touching any code.',
        resource: 'The Illustrated Transformer (jalammar.github.io)',
        url: 'https://jalammar.github.io/illustrated-transformer/',
        type: 'article',
      },
      {
        step: 2, level: 'Beginner', time: '3 hrs',
        title: 'Watch the Visual Explainers',
        description: '3Blue1Brown\'s "Attention in Transformers" and Andrej Karpathy\'s "Let\'s build GPT from scratch" build the right mental model before you read the paper.',
        resource: '3Blue1Brown · Andrej Karpathy (YouTube)',
        url: 'https://www.youtube.com/@3blue1brown',
        type: 'video',
      },
      {
        step: 3, level: 'Intermediate', time: '4 hrs',
        title: 'Read the Original Paper',
        description: 'Work through "Attention Is All You Need" alongside the Harvard annotated implementation — each line of code maps to a section of the paper.',
        resource: 'arxiv.org/abs/1706.03762 + nlp.seas.harvard.edu/annotated-transformer',
        url: 'https://arxiv.org/abs/1706.03762',
        type: 'paper',
      },
      {
        step: 4, level: 'Intermediate', time: '8 hrs',
        title: 'Build a Transformer from Scratch',
        description: 'Implement a character-level language model using Karpathy\'s nanoGPT. Writing the attention mechanism yourself cements the concept permanently.',
        resource: 'github.com/karpathy/nanoGPT',
        url: 'https://github.com/karpathy/nanoGPT',
        type: 'code',
      },
      {
        step: 5, level: 'Intermediate', time: '20 hrs',
        title: 'Take Stanford CS224N',
        description: 'Full NLP with Deep Learning course. Lectures 8–12 cover Transformers, pre-training, and BERT in depth with assignments.',
        resource: 'web.stanford.edu/class/cs224n',
        url: 'https://web.stanford.edu/class/cs224n/',
        type: 'course',
      },
      {
        step: 6, level: 'Advanced', time: '10 hrs',
        title: 'Read BERT and GPT-1',
        description: 'The two dominant applications of Transformers — encoder (BERT) and decoder (GPT). Understanding both architectures is essential for applied NLP.',
        resource: 'arxiv.org/abs/1810.04805 · openai.com/research',
        url: 'https://arxiv.org/abs/1810.04805',
        type: 'paper',
      },
    ],
    papers: [
      {
        title: 'Attention Is All You Need',
        authors: 'Vaswani, Shazeer, Parmar et al.',
        year: 2017, venue: 'NeurIPS 2017',
        description: 'The foundational paper introducing the Transformer architecture. Proposes replacing recurrence entirely with multi-head self-attention for sequence-to-sequence tasks. Every modern LLM traces its lineage here.',
        url: 'https://arxiv.org/abs/1706.03762',
        mustRead: true,
      },
      {
        title: 'BERT: Pre-training of Deep Bidirectional Transformers',
        authors: 'Devlin, Chang, Lee, Toutanova',
        year: 2018, venue: 'NAACL 2019',
        description: 'Introduces masked language modeling (MLM) for bidirectional pre-training. Achieves SOTA on 11 NLP tasks simultaneously. Encoder-only Transformer for understanding tasks.',
        url: 'https://arxiv.org/abs/1810.04805',
        mustRead: true,
      },
      {
        title: 'Improving Language Understanding by Generative Pre-Training (GPT-1)',
        authors: 'Radford, Narasimhan, Salimans, Sutskever',
        year: 2018, venue: 'OpenAI Blog',
        description: 'The first GPT: decoder-only Transformer pre-trained on BooksCorpus. Establishes the pre-train → fine-tune paradigm that defines the next 5 years.',
        url: 'https://openai.com/research/language-unsupervised',
        mustRead: false,
      },
      {
        title: 'Universal Transformers',
        authors: 'Dehghani, Gouws, Vinyals et al.',
        year: 2018, venue: 'ICLR 2019',
        description: 'Combines Transformer parallelism with the recurrent depth of RNNs via adaptive computation time. Bridges the gap between feed-forward and recurrent models.',
        url: 'https://arxiv.org/abs/1807.03819',
        mustRead: false,
      },
      {
        title: 'Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context',
        authors: 'Dai, Yang, Yang et al.',
        year: 2019, venue: 'ACL 2019',
        description: 'Addresses the fixed context-length limitation with a recurrence mechanism and relative positional encodings. Precursor to the long-context models of the 2020s.',
        url: 'https://arxiv.org/abs/1901.02860',
        mustRead: false,
      },
      {
        title: 'An Image is Worth 16×16 Words: Transformers for Image Recognition at Scale (ViT)',
        authors: 'Dosovitskiy, Beyer, Kolesnikov et al.',
        year: 2020, venue: 'ICLR 2021',
        description: 'Applies the Transformer directly to image patches. Demonstrates that the architecture generalizes beyond NLP to vision — the beginning of multimodal AI.',
        url: 'https://arxiv.org/abs/2010.11929',
        mustRead: false,
      },
    ],
    books: [
      {
        title: 'Natural Language Processing with Transformers',
        authors: 'Lewis Tunstall, Leandro von Werra, Thomas Wolf',
        year: 2022, level: 'Intermediate',
        description: 'The definitive practical guide to working with Transformers using Hugging Face. Covers fine-tuning, text classification, NER, summarization, and more with hands-on code.',
        publisher: "O'Reilly Media",
      },
      {
        title: 'Deep Learning',
        authors: 'Ian Goodfellow, Yoshua Bengio, Aaron Courville',
        year: 2016, level: 'Advanced',
        description: 'The mathematical foundation required to understand Transformer internals — backpropagation, optimization, regularization, and sequence modeling. Free online.',
        publisher: 'MIT Press',
        url: 'https://www.deeplearningbook.org/',
      },
      {
        title: 'Speech and Language Processing (3rd ed.)',
        authors: 'Daniel Jurafsky, James H. Martin',
        year: 2023, level: 'Intermediate',
        description: 'Comprehensive NLP textbook with dedicated chapters on Transformers, BERT, and large language models. Free draft available online. Standard graduate-level reference.',
        publisher: 'Pearson',
        url: 'https://web.stanford.edu/~jurafsky/slp3/',
      },
      {
        title: 'Dive into Deep Learning',
        authors: 'Zhang, Lipton, Li, Smola',
        year: 2023, level: 'Intermediate',
        description: 'Interactive textbook with full code in PyTorch, TensorFlow, and JAX. Chapter 11 covers the Transformer in complete detail with runnable notebooks.',
        publisher: 'Cambridge University Press',
        url: 'https://d2l.ai/',
      },
    ],
    visual: [
      {
        title: 'The Illustrated Transformer',
        creator: 'Jay Alammar',
        type: 'Article', year: 2018,
        description: 'The single best visual explanation of how Transformers work. Step-by-step diagrams of self-attention, multi-head attention, and the encoder-decoder stack.',
        url: 'https://jalammar.github.io/illustrated-transformer/',
      },
      {
        title: 'Attention in Transformers, Visually Explained',
        creator: '3Blue1Brown',
        type: 'Video', year: 2024,
        description: 'Grant Sanderson\'s characteristic visual style applied to attention mechanisms. Best entry point for viewers who prefer animation over static diagrams.',
        url: 'https://www.youtube.com/@3blue1brown',
      },
      {
        title: "Let's build GPT: from scratch, in code, spelled out",
        creator: 'Andrej Karpathy',
        type: 'Video', year: 2023,
        description: '2-hour deep-dive coding session implementing a GPT character-level model live. Widely considered the best "build to understand" resource for Transformers.',
        url: 'https://www.youtube.com/@AndrejKarpathy',
      },
      {
        title: '"Attention Is All You Need" Paper Explained',
        creator: 'Yannic Kilcher',
        type: 'Video', year: 2020,
        description: 'Line-by-line walkthrough of the original paper with Yannic\'s commentary. Essential if you want to understand every architectural decision and why it was made.',
        url: 'https://www.youtube.com/@YannicKilcher',
      },
      {
        title: 'Transformer Explainer (Interactive)',
        creator: 'Polo Club of Data Science, Georgia Tech',
        type: 'Interactive', year: 2024,
        description: 'Live, in-browser interactive visualization of a GPT-2 small model. Watch attention patterns form as you type. Best tool for building intuition.',
        url: 'https://poloclub.github.io/transformer-explainer/',
      },
    ],
    code: [
      {
        name: 'The Annotated Transformer',
        org: 'Harvard NLP',
        language: 'Python / PyTorch', stars: '5k+',
        description: 'The "Attention Is All You Need" paper presented as a fully annotated, runnable Python implementation. Every formula maps to code. Essential companion to the original paper.',
        url: 'https://nlp.seas.harvard.edu/annotated-transformer/',
      },
      {
        name: 'nanoGPT',
        org: 'Andrej Karpathy',
        language: 'Python / PyTorch', stars: '40k+',
        description: 'The simplest, fastest repository for training medium-sized GPTs. ~300 lines of core code. Ideal for understanding training dynamics and the decoder-only architecture.',
        url: 'https://github.com/karpathy/nanoGPT',
      },
      {
        name: 'transformers',
        org: 'Hugging Face',
        language: 'Python', stars: '140k+',
        description: 'The standard library for working with pre-trained Transformers. 300+ architectures, 500k+ models. Start here for any production NLP or multimodal task.',
        url: 'https://github.com/huggingface/transformers',
      },
      {
        name: 'minGPT',
        org: 'Andrej Karpathy',
        language: 'Python / PyTorch', stars: '20k+',
        description: 'Minimal (~300 line) PyTorch re-implementation of GPT for educational purposes. Cleaner and more commented than nanoGPT — ideal first read before nanoGPT.',
        url: 'https://github.com/karpathy/minGPT',
      },
      {
        name: 'tensor2tensor',
        org: 'Google Research',
        language: 'Python / TensorFlow', stars: '15k+',
        description: 'The original implementation used to train the Transformer in the 2017 paper. Historical reference — understand what the authors actually ran.',
        url: 'https://github.com/tensorflow/tensor2tensor',
      },
    ],
    byYear: [
      {
        year: '2017',
        items: [
          { title: 'Attention Is All You Need', type: 'Paper', url: 'https://arxiv.org/abs/1706.03762' },
          { title: 'The Illustrated Transformer (Alammar)', type: 'Article', url: 'https://jalammar.github.io/illustrated-transformer/' },
        ],
      },
      {
        year: '2018',
        items: [
          { title: 'BERT (Devlin et al.)', type: 'Paper', url: 'https://arxiv.org/abs/1810.04805' },
          { title: 'GPT-1 (OpenAI)', type: 'Paper', url: 'https://openai.com/research/language-unsupervised' },
          { title: 'Universal Transformers', type: 'Paper', url: 'https://arxiv.org/abs/1807.03819' },
          { title: 'The Illustrated BERT (Alammar)', type: 'Article', url: 'https://jalammar.github.io/illustrated-bert/' },
        ],
      },
      {
        year: '2019',
        items: [
          { title: 'GPT-2 (OpenAI)', type: 'Paper', url: 'https://openai.com/research/better-language-models' },
          { title: 'Transformer-XL', type: 'Paper', url: 'https://arxiv.org/abs/1901.02860' },
          { title: 'XLNet', type: 'Paper', url: 'https://arxiv.org/abs/1906.08237' },
          { title: 'RoBERTa', type: 'Paper', url: 'https://arxiv.org/abs/1907.11692' },
        ],
      },
      {
        year: '2020',
        items: [
          { title: 'Exploring the Limits of Transfer Learning (T5)', type: 'Paper', url: 'https://arxiv.org/abs/1910.10683' },
          { title: 'ViT — Transformers for Vision', type: 'Paper', url: 'https://arxiv.org/abs/2010.11929' },
          { title: 'minGPT (Karpathy)', type: 'Code', url: 'https://github.com/karpathy/minGPT' },
        ],
      },
    ],
  },

  2: {
    path: [
      {
        step: 1, level: 'Beginner', time: '1 hr',
        title: 'Use GPT-4 and Claude to Build Intuition',
        description: 'Before reading any theory, spend an hour prompting ChatGPT and Claude with diverse tasks. Observe what they do well and where they fail. This grounds all subsequent learning.',
        resource: 'chat.openai.com · claude.ai',
        url: 'https://chat.openai.com',
        type: 'tool',
      },
      {
        step: 2, level: 'Beginner', time: '3 hrs',
        title: 'Understand Foundation Models and Scaling Laws',
        description: 'Read Sebastion Raschka\'s "Build a Large Language Model From Scratch" first two chapters, plus the original GPT-3 paper introduction. Understand why scale matters.',
        resource: 'arxiv.org/abs/2005.14165 (GPT-3)',
        url: 'https://arxiv.org/abs/2005.14165',
        type: 'paper',
      },
      {
        step: 3, level: 'Intermediate', time: '8 hrs',
        title: 'Complete the Hugging Face NLP Course',
        description: 'Free, hands-on course covering: Transformers pipeline, fine-tuning, datasets, tokenizers, and the full Hugging Face ecosystem. The practical foundation for GenAI work.',
        resource: 'huggingface.co/learn/nlp-course',
        url: 'https://huggingface.co/learn/nlp-course',
        type: 'course',
      },
      {
        step: 4, level: 'Intermediate', time: '5 hrs',
        title: 'Learn Prompt Engineering',
        description: 'Read the OpenAI Prompt Engineering Guide and Anthropic\'s prompt engineering documentation. Systematic prompting is the primary interface to generative models.',
        resource: 'platform.openai.com/docs/guides/prompt-engineering',
        url: 'https://platform.openai.com/docs/guides/prompt-engineering',
        type: 'guide',
      },
      {
        step: 5, level: 'Intermediate', time: '6 hrs',
        title: 'Understand RLHF and Alignment',
        description: 'Read InstructGPT and Constitutional AI papers. RLHF is the technique that made ChatGPT safe and useful — understanding it is essential for production LLM work.',
        resource: 'arxiv.org/abs/2203.02155 (InstructGPT)',
        url: 'https://arxiv.org/abs/2203.02155',
        type: 'paper',
      },
      {
        step: 6, level: 'Advanced', time: '15 hrs',
        title: 'Build an LLM from Scratch',
        description: 'Work through Sebastian Raschka\'s "Build a Large Language Model From Scratch" completely — implement tokenization, attention, training loop, and RLHF fine-tuning from first principles.',
        resource: 'github.com/rasbt/LLMs-from-scratch',
        url: 'https://github.com/rasbt/LLMs-from-scratch',
        type: 'code',
      },
    ],
    papers: [
      {
        title: 'Language Models are Few-Shot Learners (GPT-3)',
        authors: 'Brown, Mann, Ryder et al. (OpenAI)',
        year: 2020, venue: 'NeurIPS 2020',
        description: 'The 175B parameter model that demonstrated in-context learning as an emergent capability. Few-shot prompting with no gradient updates — a paradigm shift. 1000+ citations within one year.',
        url: 'https://arxiv.org/abs/2005.14165',
        mustRead: true,
      },
      {
        title: 'Training Language Models to Follow Instructions with Human Feedback (InstructGPT)',
        authors: 'Ouyang, Wu, Jiang et al. (OpenAI)',
        year: 2022, venue: 'NeurIPS 2022',
        description: 'The RLHF paper that made GPT-3 into ChatGPT. Demonstrates that a 1.3B aligned model outperforms 175B unaligned on human preference. Defines the modern LLM training pipeline.',
        url: 'https://arxiv.org/abs/2203.02155',
        mustRead: true,
      },
      {
        title: 'Constitutional AI: Harmlessness from AI Feedback',
        authors: 'Bai, Jones, Ndousse et al. (Anthropic)',
        year: 2022, venue: 'Anthropic',
        description: 'Trains AI to be helpful and harmless using a set of principles ("constitution") rather than purely human labels. Introduces RLAIF (RL from AI Feedback) as a scalable alternative to RLHF.',
        url: 'https://arxiv.org/abs/2212.08073',
        mustRead: false,
      },
      {
        title: 'Scaling Laws for Neural Language Models',
        authors: 'Kaplan, McCandlish, Henighan et al. (OpenAI)',
        year: 2020, venue: 'OpenAI',
        description: 'Empirically derives power-law scaling relationships between model size, dataset size, compute budget, and loss. The theoretical foundation for why bigger models with more data keep improving.',
        url: 'https://arxiv.org/abs/2001.08361',
        mustRead: false,
      },
      {
        title: 'Sparks of Artificial General Intelligence: Early experiments with GPT-4',
        authors: 'Bubeck, Chandrasekaran, Eldan et al. (Microsoft)',
        year: 2023, venue: 'Microsoft Research',
        description: 'Comprehensive evaluation of GPT-4 across mathematics, coding, vision, medicine, law, and psychology. Argues GPT-4 demonstrates "sparks" of general intelligence.',
        url: 'https://arxiv.org/abs/2303.12528',
        mustRead: false,
      },
      {
        title: 'High-Resolution Image Synthesis with Latent Diffusion Models (Stable Diffusion)',
        authors: 'Rombach, Blattmann, Lorenz et al.',
        year: 2022, venue: 'CVPR 2022',
        description: 'Proposes diffusion in latent space rather than pixel space, making high-resolution image generation practical. The paper behind Stable Diffusion and the open-source image generation revolution.',
        url: 'https://arxiv.org/abs/2112.10752',
        mustRead: false,
      },
    ],
    books: [
      {
        title: 'Build a Large Language Model (From Scratch)',
        authors: 'Sebastian Raschka',
        year: 2024, level: 'Intermediate',
        description: 'Implements a GPT-style LLM from scratch in PyTorch, then fine-tunes it with instruction tuning and RLHF. The most complete hands-on resource for understanding the full modern LLM pipeline.',
        publisher: 'Manning Publications',
        url: 'https://github.com/rasbt/LLMs-from-scratch',
      },
      {
        title: 'Hands-On Large Language Models',
        authors: 'Jay Alammar, Maarten Grootendorst',
        year: 2024, level: 'Intermediate',
        description: 'Practical guide to using LLMs with 100+ illustrations. Covers embeddings, text classification, semantic search, fine-tuning, and building applications.',
        publisher: "O'Reilly Media",
      },
      {
        title: 'The Coming Wave',
        authors: 'Mustafa Suleyman',
        year: 2023, level: 'Beginner',
        description: 'Co-founder of DeepMind and Inflection AI on the trajectory of AI and synthetic biology. Accessible strategic framing of the generative AI era and its implications.',
        publisher: 'Crown',
      },
      {
        title: 'Designing Machine Learning Systems',
        authors: 'Chip Huyen',
        year: 2022, level: 'Intermediate',
        description: 'Production ML systems design — data pipelines, feature engineering, model serving, monitoring. Essential foundation for deploying generative AI in production.',
        publisher: "O'Reilly Media",
      },
    ],
    visual: [
      {
        title: 'Illustrated Stable Diffusion',
        creator: 'Jay Alammar',
        type: 'Article', year: 2022,
        description: 'Step-by-step visual guide to how diffusion models generate images — denoising, latent space, CLIP conditioning. Best introduction to the image generation side of Gen AI.',
        url: 'https://jalammar.github.io/illustrated-stable-diffusion/',
      },
      {
        title: 'But what is a GPT? Visual intro to Transformers',
        creator: '3Blue1Brown',
        type: 'Video', year: 2024,
        description: 'Visual explanation of how GPT works — embedding space, attention, feedforward layers. Part of a deep-learning series that builds up from first principles.',
        url: 'https://www.youtube.com/@3blue1brown',
      },
      {
        title: 'RLHF: Reinforcement Learning from Human Feedback',
        creator: 'Hugging Face',
        type: 'Article', year: 2023,
        description: 'Illustrated guide to the three-stage RLHF pipeline: supervised fine-tuning, reward modeling, PPO optimization. Includes code examples with trl library.',
        url: 'https://huggingface.co/blog/rlhf',
      },
      {
        title: 'A Visual Guide to Quantization',
        creator: 'Maarten Grootendorst',
        type: 'Article', year: 2024,
        description: 'Explains how LLMs are compressed to run on consumer hardware. Covers INT8, INT4, GGUF, and GPTQ quantization with visual diagrams.',
        url: 'https://newsletter.maartengrootendorst.com/p/a-visual-guide-to-quantization',
      },
      {
        title: 'LLM Visualization',
        creator: 'Brendan Bycroft',
        type: 'Interactive', year: 2023,
        description: '3D interactive visualization of a complete GPT-2 forward pass. Every matrix multiplication, every attention head, every token — rendered in real time.',
        url: 'https://bbycroft.net/llm',
      },
    ],
    code: [
      {
        name: 'LLMs-from-scratch',
        org: 'Sebastian Raschka',
        language: 'Python / PyTorch', stars: '40k+',
        description: 'Complete code for "Build a Large Language Model From Scratch." Tokenizer, GPT model, pre-training, instruction fine-tuning, RLHF — all in Jupyter notebooks.',
        url: 'https://github.com/rasbt/LLMs-from-scratch',
      },
      {
        name: 'openai-cookbook',
        org: 'OpenAI',
        language: 'Python', stars: '60k+',
        description: 'Official OpenAI recipes for common tasks: embeddings, fine-tuning, function calling, vision, and production deployment patterns.',
        url: 'https://github.com/openai/openai-cookbook',
      },
      {
        name: 'diffusers',
        org: 'Hugging Face',
        language: 'Python', stars: '27k+',
        description: 'State-of-the-art diffusion models for image, audio, and video generation. The standard library for working with Stable Diffusion and related models.',
        url: 'https://github.com/huggingface/diffusers',
      },
      {
        name: 'trl',
        org: 'Hugging Face',
        language: 'Python', stars: '12k+',
        description: 'Transformer Reinforcement Learning: RLHF, PPO, DPO, and SFT training pipelines for LLMs. The production implementation of the alignment techniques in InstructGPT.',
        url: 'https://github.com/huggingface/trl',
      },
      {
        name: 'llama.cpp',
        org: 'Georgi Gerganov',
        language: 'C++', stars: '75k+',
        description: 'Inference of LLaMA and other models in pure C++. Enables running 7B–70B models on CPU and Apple Silicon. Unlocked consumer-grade LLM usage.',
        url: 'https://github.com/ggerganov/llama.cpp',
      },
    ],
    byYear: [
      {
        year: '2018',
        items: [
          { title: 'GPT-1: Language Unsupervised (OpenAI)', type: 'Paper', url: 'https://openai.com/research/language-unsupervised' },
          { title: 'ULMFiT: Universal Language Model Fine-tuning', type: 'Paper', url: 'https://arxiv.org/abs/1801.06146' },
        ],
      },
      {
        year: '2020',
        items: [
          { title: 'GPT-3: Language Models are Few-Shot Learners', type: 'Paper', url: 'https://arxiv.org/abs/2005.14165' },
          { title: 'Scaling Laws for Neural Language Models', type: 'Paper', url: 'https://arxiv.org/abs/2001.08361' },
        ],
      },
      {
        year: '2022',
        items: [
          { title: 'InstructGPT / RLHF (OpenAI)', type: 'Paper', url: 'https://arxiv.org/abs/2203.02155' },
          { title: 'Constitutional AI (Anthropic)', type: 'Paper', url: 'https://arxiv.org/abs/2212.08073' },
          { title: 'Stable Diffusion — Latent Diffusion Models', type: 'Paper', url: 'https://arxiv.org/abs/2112.10752' },
          { title: 'ChatGPT launches (Nov 2022)', type: 'Product', url: 'https://openai.com/blog/chatgpt' },
        ],
      },
      {
        year: '2023',
        items: [
          { title: 'GPT-4 Technical Report', type: 'Paper', url: 'https://arxiv.org/abs/2303.08774' },
          { title: 'LLaMA: Open Foundation Language Models (Meta)', type: 'Paper', url: 'https://arxiv.org/abs/2302.13971' },
          { title: 'Sparks of AGI — GPT-4 Evaluation (Microsoft)', type: 'Paper', url: 'https://arxiv.org/abs/2303.12528' },
          { title: 'Hugging Face NLP Course (Free)', type: 'Course', url: 'https://huggingface.co/learn/nlp-course' },
        ],
      },
    ],
  },

  3: {
    path: [
      {
        step: 1, level: 'Beginner', time: '2 hrs',
        title: 'Understand What an Agent Is',
        description: 'Read LangChain\'s agent conceptual guide and Lilian Weng\'s "LLM Powered Autonomous Agents" blog post. Build the mental model before touching code.',
        resource: 'lilianweng.github.io/posts/2023-06-23-agent',
        url: 'https://lilianweng.github.io/posts/2023-06-23-agent/',
        type: 'article',
      },
      {
        step: 2, level: 'Beginner', time: '3 hrs',
        title: 'Read the ReAct Paper',
        description: 'ReAct is the foundation of modern agent loops. Read the paper, then implement a simple Thought→Action→Observation loop manually with the OpenAI API before using any framework.',
        resource: 'arxiv.org/abs/2210.03629',
        url: 'https://arxiv.org/abs/2210.03629',
        type: 'paper',
      },
      {
        step: 3, level: 'Intermediate', time: '8 hrs',
        title: 'DeepLearning.AI: Functions, Tools and Agents with LangChain',
        description: 'Andrew Ng + Harrison Chase course covering function calling, tools, agents, and multi-agent workflows. Free short course — the fastest route to practical agent development.',
        resource: 'learn.deeplearning.ai',
        url: 'https://learn.deeplearning.ai',
        type: 'course',
      },
      {
        step: 4, level: 'Intermediate', time: '10 hrs',
        title: 'Build Agents with LangChain and OpenAI Tools',
        description: 'Work through the LangChain agent documentation and cookbook. Build: a web-search agent, a code-execution agent, and a multi-tool research agent.',
        resource: 'python.langchain.com/docs/concepts/agents',
        url: 'https://python.langchain.com/docs/concepts/agents',
        type: 'guide',
      },
      {
        step: 5, level: 'Intermediate', time: '6 hrs',
        title: 'Study Multi-Agent Patterns with CrewAI',
        description: 'CrewAI\'s role-based multi-agent framework maps directly to the digital workforce model. Build a research + writing crew to understand supervisor-worker agent patterns.',
        resource: 'docs.crewai.com',
        url: 'https://docs.crewai.com',
        type: 'guide',
      },
      {
        step: 6, level: 'Advanced', time: '8 hrs',
        title: 'Read Reflexion and Implement Self-Improving Agents',
        description: 'The Reflexion paper shows how agents that critique and revise their own outputs dramatically outperform those that don\'t. Implement a self-reflective coding agent.',
        resource: 'arxiv.org/abs/2303.11366',
        url: 'https://arxiv.org/abs/2303.11366',
        type: 'paper',
      },
    ],
    papers: [
      {
        title: 'ReAct: Synergizing Reasoning and Acting in Language Models',
        authors: 'Yao, Zhao, Yu et al. (Princeton/Google)',
        year: 2022, venue: 'ICLR 2023',
        description: 'Proposes interleaving chain-of-thought reasoning with action execution. The agent loop — Thought, Action, Observation — that every modern agent framework implements. Start here.',
        url: 'https://arxiv.org/abs/2210.03629',
        mustRead: true,
      },
      {
        title: 'Chain-of-Thought Prompting Elicits Reasoning in Large Language Models',
        authors: 'Wei, Wang, Schuurmans et al. (Google)',
        year: 2022, venue: 'NeurIPS 2022',
        description: 'Demonstrates that prompting models to "think step by step" dramatically improves multi-step reasoning performance. The theoretical basis for CoT agents.',
        url: 'https://arxiv.org/abs/2201.11903',
        mustRead: true,
      },
      {
        title: 'Reflexion: Language Agents with Verbal Reinforcement Learning',
        authors: 'Shinn, Cassano, Gopinath et al.',
        year: 2023, venue: 'NeurIPS 2023',
        description: 'Agents that reflect on past failures using verbal feedback improve significantly on coding and decision-making benchmarks. Self-critique as a first-class agent capability.',
        url: 'https://arxiv.org/abs/2303.11366',
        mustRead: false,
      },
      {
        title: 'Tree of Thoughts: Deliberate Problem Solving with Large Language Models',
        authors: 'Yao, Yu, Zhao et al.',
        year: 2023, venue: 'NeurIPS 2023',
        description: 'Extends CoT to a tree structure — the model explores multiple reasoning paths and backtracks when needed. Dramatically improves performance on complex planning tasks.',
        url: 'https://arxiv.org/abs/2305.10601',
        mustRead: false,
      },
      {
        title: 'Toolformer: Language Models Can Teach Themselves to Use Tools',
        authors: 'Schick, Dwivedi-Kumar, Dessì et al. (Meta)',
        year: 2023, venue: 'NeurIPS 2023',
        description: 'LLMs that learn when and how to call tools by self-supervising on tool call examples. Foundational for understanding the "tool use as learned behavior" paradigm.',
        url: 'https://arxiv.org/abs/2302.04761',
        mustRead: false,
      },
      {
        title: 'LLM Powered Autonomous Agents',
        authors: 'Lilian Weng (OpenAI)',
        year: 2023, venue: 'OpenAI Blog',
        description: 'Comprehensive survey of agent architectures — planning, memory, tool use, and multi-agent systems. The canonical reference blog post that synthesized the agentic AI moment.',
        url: 'https://lilianweng.github.io/posts/2023-06-23-agent/',
        mustRead: true,
      },
    ],
    books: [
      {
        title: 'AI Engineering',
        authors: 'Chip Huyen',
        year: 2025, level: 'Intermediate',
        description: 'Production-grade LLM application development: RAG, agents, evals, and deployment. The definitive engineering guide for building reliable AI systems beyond demos.',
        publisher: "O'Reilly Media",
      },
      {
        title: 'Prompt Engineering for LLMs',
        authors: 'John Berryman, Albert Ziegler',
        year: 2024, level: 'Beginner',
        description: 'Practical prompt engineering patterns for agents, chains, and structured outputs. Bridges the gap between prompt intuition and systematic agent design.',
        publisher: "O'Reilly Media",
      },
      {
        title: 'The AI-Powered Developer',
        authors: 'Nathan B. Crocker',
        year: 2024, level: 'Beginner',
        description: 'Practical guide to AI-assisted software development using LLM agents, code generation, and AI-driven debugging workflows.',
        publisher: 'Manning Publications',
      },
    ],
    visual: [
      {
        title: 'LLM Powered Autonomous Agents',
        creator: 'Lilian Weng (OpenAI)',
        type: 'Article', year: 2023,
        description: 'The definitive illustrated survey of agent architectures with diagrams covering planning, memory systems, tool use, and multi-agent coordination. Required reading for any agent engineer.',
        url: 'https://lilianweng.github.io/posts/2023-06-23-agent/',
      },
      {
        title: 'ReAct: Reasoning and Acting Explained',
        creator: 'Yannic Kilcher',
        type: 'Video', year: 2023,
        description: 'Paper walkthrough of ReAct with live demonstrations. Explains why interleaving reasoning and acting outperforms chain-of-thought alone.',
        url: 'https://www.youtube.com/@YannicKilcher',
      },
      {
        title: 'Cognitive Architectures for Language Agents (Survey)',
        creator: 'Sumers, Yao, Narasimhan et al.',
        type: 'Article', year: 2023,
        description: 'Visual taxonomy of agent architectures mapped to cognitive science models. Best reference for understanding the design space of agentic AI systems.',
        url: 'https://arxiv.org/abs/2309.02427',
      },
      {
        title: 'What are AI Agents? (DeepLearning.AI)',
        creator: 'Andrew Ng',
        type: 'Video', year: 2024,
        description: 'Andrew Ng\'s concise visual explanation of AI agents, agentic patterns (reflection, tool use, planning, multi-agent), and why they represent a new AI paradigm.',
        url: 'https://www.deeplearning.ai',
      },
    ],
    code: [
      {
        name: 'langchain',
        org: 'LangChain',
        language: 'Python', stars: '100k+',
        description: 'The dominant framework for building LLM-powered agents and chains. Agents, tools, memory, RAG, callbacks — the broadest ecosystem for production agent development.',
        url: 'https://github.com/langchain-ai/langchain',
      },
      {
        name: 'crewAI',
        org: 'CrewAI Inc.',
        language: 'Python', stars: '28k+',
        description: 'Role-based multi-agent orchestration. Define agents with roles, goals, and backstories; assign tasks; run collaborative crews. Production-friendly and well-documented.',
        url: 'https://github.com/crewAIInc/crewAI',
      },
      {
        name: 'autogen',
        org: 'Microsoft',
        language: 'Python', stars: '38k+',
        description: 'Multi-agent conversation framework where agents can have code-execution capabilities. Strong research pedigree; includes GroupChat for N-agent coordination.',
        url: 'https://github.com/microsoft/autogen',
      },
      {
        name: 'Auto-GPT',
        org: 'Significant Gravitas',
        language: 'Python', stars: '170k+',
        description: 'The first viral autonomous agent (April 2023). Demonstrated long-horizon autonomous operation. Historical significance — the project that made the world aware of AI agents.',
        url: 'https://github.com/Significant-Gravitas/AutoGPT',
      },
      {
        name: 'openai-agents-python',
        org: 'OpenAI',
        language: 'Python', stars: '10k+',
        description: 'OpenAI\'s official lightweight framework for building multi-agent workflows. Handoffs, guardrails, tracing — production patterns directly from OpenAI.',
        url: 'https://github.com/openai/openai-agents-python',
      },
    ],
    byYear: [
      {
        year: '2022',
        items: [
          { title: 'Chain-of-Thought Prompting (Google)', type: 'Paper', url: 'https://arxiv.org/abs/2201.11903' },
          { title: 'ReAct: Synergizing Reasoning and Acting', type: 'Paper', url: 'https://arxiv.org/abs/2210.03629' },
          { title: 'Toolformer (Meta AI)', type: 'Paper', url: 'https://arxiv.org/abs/2302.04761' },
        ],
      },
      {
        year: '2023 Q1',
        items: [
          { title: 'AutoGPT goes viral — first autonomous agent', type: 'Project', url: 'https://github.com/Significant-Gravitas/AutoGPT' },
          { title: 'BabyAGI — task management agent', type: 'Project', url: 'https://github.com/yoheinakajima/babyagi' },
          { title: 'Tree of Thoughts', type: 'Paper', url: 'https://arxiv.org/abs/2305.10601' },
        ],
      },
      {
        year: '2023 Q2–Q4',
        items: [
          { title: 'OpenAI Function Calling API', type: 'Product', url: 'https://platform.openai.com/docs/guides/function-calling' },
          { title: 'Reflexion Paper', type: 'Paper', url: 'https://arxiv.org/abs/2303.11366' },
          { title: 'LLM Powered Autonomous Agents (Weng)', type: 'Article', url: 'https://lilianweng.github.io/posts/2023-06-23-agent/' },
          { title: 'OpenAI Assistants API', type: 'Product', url: 'https://platform.openai.com/docs/assistants/overview' },
        ],
      },
      {
        year: '2024',
        items: [
          { title: 'DeepLearning.AI: AI Agents in LangGraph (Course)', type: 'Course', url: 'https://learn.deeplearning.ai' },
          { title: 'Devin — Autonomous Software Engineer', type: 'Product', url: 'https://www.cognition.ai/blog/introducing-devin' },
          { title: 'CrewAI reaches 1M downloads', type: 'Milestone', url: 'https://github.com/crewAIInc/crewAI' },
        ],
      },
    ],
  },

  4: {
    path: [
      {
        step: 1, level: 'Beginner', time: '2 hrs',
        title: 'Read the Compound AI Systems Blog',
        description: 'Berkeley BAIR\'s "The Shift from Models to Compound AI Systems" defines this era. Understand why combining multiple AI components outperforms any single model.',
        resource: 'bair.berkeley.edu/blog/2024/02/18/compound-ai-systems',
        url: 'https://bair.berkeley.edu/blog/2024/02/18/compound-ai-systems/',
        type: 'article',
      },
      {
        step: 2, level: 'Intermediate', time: '8 hrs',
        title: 'DeepLearning.AI: Building and Evaluating Advanced RAG',
        description: 'Advanced RAG patterns: query rewriting, re-ranking, HyDE, recursive retrieval. RAG is the foundational retrieval layer in all compound AI systems.',
        resource: 'learn.deeplearning.ai',
        url: 'https://learn.deeplearning.ai',
        type: 'course',
      },
      {
        step: 3, level: 'Intermediate', time: '10 hrs',
        title: 'LangGraph Academy: Introduction to LangGraph',
        description: 'Official LangGraph course covering stateful graph workflows, checkpointing, human-in-the-loop, and multi-agent architectures. LangGraph is the standard for complex orchestrated systems.',
        resource: 'academy.langchain.com',
        url: 'https://academy.langchain.com',
        type: 'course',
      },
      {
        step: 4, level: 'Intermediate', time: '4 hrs',
        title: 'Implement the Model Context Protocol',
        description: 'Build an MCP server using the official TypeScript or Python SDK. MCP is the universal standard for connecting models to tools — essential for compound system interoperability.',
        resource: 'modelcontextprotocol.io',
        url: 'https://modelcontextprotocol.io',
        type: 'guide',
      },
      {
        step: 5, level: 'Advanced', time: '8 hrs',
        title: 'Build an LLM Evaluation Pipeline',
        description: 'Use LangSmith or Ragas to build a systematic evaluation pipeline. LLM-as-judge with structured rubrics is the production standard for compound AI quality assurance.',
        resource: 'docs.smith.langchain.com',
        url: 'https://docs.smith.langchain.com',
        type: 'guide',
      },
      {
        step: 6, level: 'Advanced', time: '10 hrs',
        title: 'DSPy: Programmatic LLM Pipelines',
        description: 'DSPy replaces brittle prompt strings with compiled programs that automatically optimize prompts and few-shot examples. Represents the frontier of compound AI system design.',
        resource: 'github.com/stanfordnlp/dspy',
        url: 'https://github.com/stanfordnlp/dspy',
        type: 'code',
      },
    ],
    papers: [
      {
        title: 'The Shift from Models to Compound AI Systems',
        authors: 'Zaharia, Chen, Davis et al. (Berkeley BAIR)',
        year: 2024, venue: 'BAIR Blog',
        description: 'Defines "compound AI systems" as the new frontier: systems that combine multiple model calls, retrievers, caches, and control logic. The canonical framing of this era.',
        url: 'https://bair.berkeley.edu/blog/2024/02/18/compound-ai-systems/',
        mustRead: true,
      },
      {
        title: 'Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena',
        authors: 'Zheng, Chiang, Sheng et al. (Berkeley)',
        year: 2023, venue: 'NeurIPS 2023',
        description: 'Validates LLM-as-a-Judge as a reliable evaluation method. Introduces MT-Bench and Chatbot Arena. The paper that established LLM judges as a production evaluation standard.',
        url: 'https://arxiv.org/abs/2306.05685',
        mustRead: true,
      },
      {
        title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        authors: 'Lewis, Perez, Piktus et al. (Facebook)',
        year: 2020, venue: 'NeurIPS 2020',
        description: 'The original RAG paper. Combines dense retrieval with seq2seq generation. Foundational for all knowledge-augmented compound AI systems.',
        url: 'https://arxiv.org/abs/2005.11401',
        mustRead: false,
      },
      {
        title: 'DSPy: Compiling Declarative Language Model Calls into State-of-the-Art Pipelines',
        authors: 'Khattab, Singhvi, Maheshwari et al. (Stanford)',
        year: 2023, venue: 'ICLR 2024',
        description: 'Proposes DSPy — treat LLM pipelines as programs, optimize prompts and weights automatically using a compiler. Replaces fragile hand-crafted prompts with programmatic pipelines.',
        url: 'https://arxiv.org/abs/2310.03714',
        mustRead: false,
      },
      {
        title: 'Model Context Protocol Specification',
        authors: 'Anthropic',
        year: 2024, venue: 'Anthropic',
        description: 'The open standard for connecting AI models to tools, data sources, and services. Defines the universal plug-and-play protocol for compound AI system integrations.',
        url: 'https://modelcontextprotocol.io/specification',
        mustRead: false,
      },
    ],
    books: [
      {
        title: 'AI Engineering',
        authors: 'Chip Huyen',
        year: 2025, level: 'Intermediate',
        description: 'Comprehensive guide to production AI systems — RAG, agents, evaluation, fine-tuning, and deployment. The definitive engineering reference for compound AI systems.',
        publisher: "O'Reilly Media",
      },
      {
        title: 'Building LLM-Powered Applications',
        authors: 'Valentina Alto',
        year: 2024, level: 'Intermediate',
        description: 'Practical guide to building compound AI applications with LangChain, LlamaIndex, and Azure OpenAI. Covers RAG, agents, and enterprise deployment patterns.',
        publisher: 'Packt Publishing',
      },
      {
        title: 'Developing Apps with GPT-4 and ChatGPT',
        authors: 'Olivier Caelen, Marie-Alice Blete',
        year: 2023, level: 'Beginner',
        description: 'Entry-level guide to building AI applications. Good for developers new to LLM application development who want to understand the full stack.',
        publisher: "O'Reilly Media",
      },
    ],
    visual: [
      {
        title: 'Visual Guide to RAG',
        creator: 'Maarten Grootendorst',
        type: 'Article', year: 2024,
        description: 'Step-by-step illustrated guide to RAG pipelines — chunking, embedding, retrieval, reranking, generation. Includes comparison of naive vs. advanced RAG patterns.',
        url: 'https://newsletter.maartengrootendorst.com',
      },
      {
        title: 'LangGraph Concepts Visualized',
        creator: 'LangChain',
        type: 'Article', year: 2024,
        description: 'Official visual documentation for LangGraph — state graph structure, node execution, conditional edges, and checkpointing patterns.',
        url: 'https://langchain-ai.github.io/langgraph/concepts/',
      },
      {
        title: 'Introduction to MCP — Model Context Protocol',
        creator: 'Anthropic',
        type: 'Article', year: 2024,
        description: 'Official explainer with architecture diagrams showing how MCP clients, servers, and hosts interact. The primary reference for MCP ecosystem understanding.',
        url: 'https://modelcontextprotocol.io/introduction',
      },
      {
        title: 'A Survey of Techniques for Maximizing LLM Performance',
        creator: 'OpenAI',
        type: 'Video', year: 2023,
        description: 'OpenAI DevDay talk covering prompting, RAG, and fine-tuning decision trees. Decision framework for choosing compound AI architecture patterns.',
        url: 'https://www.youtube.com/watch?v=ahnGLM-RC1Y',
      },
    ],
    code: [
      {
        name: 'langgraph',
        org: 'LangChain',
        language: 'Python', stars: '12k+',
        description: 'Stateful, multi-actor workflows for LLMs. The standard production framework for complex orchestrated AI systems with checkpointing and human-in-the-loop support.',
        url: 'https://github.com/langchain-ai/langgraph',
      },
      {
        name: 'llama_index',
        org: 'LlamaIndex',
        language: 'Python', stars: '40k+',
        description: 'Data framework for LLM applications — RAG pipelines, knowledge graphs, agentic RAG. Enterprise-oriented with strong connectors to external data sources.',
        url: 'https://github.com/run-llama/llama_index',
      },
      {
        name: 'dspy',
        org: 'Stanford NLP',
        language: 'Python', stars: '22k+',
        description: 'Programming framework for LLM pipelines. Compiles declarative module definitions into optimized prompts automatically. Represents the most principled approach to compound AI.',
        url: 'https://github.com/stanfordnlp/dspy',
      },
      {
        name: 'ragas',
        org: 'Exploding Gradients',
        language: 'Python', stars: '8k+',
        description: 'Evaluation framework for RAG pipelines — faithfulness, answer relevance, context precision, context recall. Production evaluation for knowledge-augmented systems.',
        url: 'https://github.com/explodinggradients/ragas',
      },
      {
        name: 'anthropic-cookbook',
        org: 'Anthropic',
        language: 'Python', stars: '10k+',
        description: 'Official recipes for building with Claude — tool use, prompt caching, vision, MCP integration. Best practices directly from Anthropic engineers.',
        url: 'https://github.com/anthropics/anthropic-cookbook',
      },
    ],
    byYear: [
      {
        year: '2024 Q1',
        items: [
          { title: 'Compound AI Systems (Berkeley BAIR)', type: 'Article', url: 'https://bair.berkeley.edu/blog/2024/02/18/compound-ai-systems/' },
          { title: 'LangGraph 0.1 — stateful agent workflows', type: 'Release', url: 'https://github.com/langchain-ai/langgraph' },
          { title: 'Claude 3 Opus — SOTA reasoning', type: 'Product', url: 'https://www.anthropic.com/news/claude-3-family' },
        ],
      },
      {
        year: '2024 Q2–Q3',
        items: [
          { title: 'GPT-4o — multimodal, real-time voice', type: 'Product', url: 'https://openai.com/index/hello-gpt-4o/' },
          { title: 'LLaMA 3 — open-weight GPT-4 class', type: 'Release', url: 'https://ai.meta.com/blog/meta-llama-3/' },
          { title: 'Gemini 1.5 Pro — 1M token context', type: 'Product', url: 'https://blog.google/technology/ai/google-gemini-next-generation-model-february-2024/' },
        ],
      },
      {
        year: '2024 Q4',
        items: [
          { title: 'Model Context Protocol (Anthropic)', type: 'Standard', url: 'https://modelcontextprotocol.io' },
          { title: 'o1 / Reasoning Models (OpenAI)', type: 'Product', url: 'https://openai.com/o1' },
          { title: 'Claude 3.5 Sonnet — computer use', type: 'Product', url: 'https://www.anthropic.com/news/claude-3-5-sonnet' },
        ],
      },
    ],
  },

  5: {
    path: [
      {
        step: 1, level: 'Beginner', time: '2 hrs',
        title: 'Understand the Digital Workforce Paradigm',
        description: 'Read Salesforce Agentforce documentation and Microsoft\'s Copilot Wave 2 blog. Understand how enterprises frame AI agents as workforce members, not tools.',
        resource: 'agent.salesforce.com · microsoft.com/copilot',
        url: 'https://www.salesforce.com/agentforce/',
        type: 'article',
      },
      {
        step: 2, level: 'Beginner', time: '3 hrs',
        title: 'CrewAI Quickstart: Build Your First Crew',
        description: 'Complete the CrewAI quickstart — build a research + writing crew with defined roles, goals, and task delegation. Immediately internalize the "worker with a role" mental model.',
        resource: 'docs.crewai.com/quickstart',
        url: 'https://docs.crewai.com/quickstart',
        type: 'guide',
      },
      {
        step: 3, level: 'Intermediate', time: '6 hrs',
        title: 'Multi-AI Agent Systems (DeepLearning.AI)',
        description: 'Short course by João Moura (CrewAI founder). Covers role-based agents, task delegation, multi-agent pipelines, and worker governance patterns.',
        resource: 'learn.deeplearning.ai',
        url: 'https://learn.deeplearning.ai',
        type: 'course',
      },
      {
        step: 4, level: 'Intermediate', time: '8 hrs',
        title: 'Build a Multi-Worker Business Pipeline',
        description: 'Build a crew with a ResearchAgent, AnalysisAgent, WriterAgent, and ReviewerAgent. Implement task dependencies, output handoffs, and quality gates between workers.',
        resource: 'docs.crewai.com/examples',
        url: 'https://docs.crewai.com/examples/example',
        type: 'code',
      },
      {
        step: 5, level: 'Intermediate', time: '5 hrs',
        title: 'Worker Governance: Permissions and Tool Access',
        description: 'Implement per-worker tool permissions and escalation rules. Read the AutoGen agent groupchat documentation for authority hierarchies in multi-agent systems.',
        resource: 'microsoft.github.io/autogen',
        url: 'https://microsoft.github.io/autogen/',
        type: 'guide',
      },
      {
        step: 6, level: 'Advanced', time: '10 hrs',
        title: 'Agent Evals: Measuring Digital Worker Performance',
        description: 'Build evaluation harnesses for multi-agent workflows using AgentBench or GAIA. Measuring worker performance is prerequisite to governing a digital workforce.',
        resource: 'github.com/THUDM/AgentBench',
        url: 'https://github.com/THUDM/AgentBench',
        type: 'code',
      },
    ],
    papers: [
      {
        title: 'AgentBench: Evaluating LLMs as Agents',
        authors: 'Liu, Yu, Zhang et al. (Tsinghua)',
        year: 2023, venue: 'ICLR 2024',
        description: 'Comprehensive benchmark for evaluating AI agents across 8 distinct environments. Establishes systematic evaluation methodology for AI digital workers.',
        url: 'https://arxiv.org/abs/2308.03688',
        mustRead: true,
      },
      {
        title: 'AutoGen: Enabling Next-Gen LLM Applications via Multi-Agent Conversation',
        authors: 'Wu, Bansal, Zhang et al. (Microsoft)',
        year: 2023, venue: 'COLM 2024',
        description: 'Introduces the multi-agent conversation framework where customizable agents collaborate via automated conversations to solve tasks. Foundation for workforce-style AI systems.',
        url: 'https://arxiv.org/abs/2308.08155',
        mustRead: true,
      },
      {
        title: 'GAIA: A Benchmark for General AI Assistants',
        authors: 'Mialon, Fourrier, Swift et al.',
        year: 2023, venue: 'ICLR 2024',
        description: 'Real-world benchmark requiring AI workers to use tools, browse the web, process files, and reason across multiple steps. Measures practical digital worker capability.',
        url: 'https://arxiv.org/abs/2311.12983',
        mustRead: false,
      },
      {
        title: 'Communicative Agents for Software Development',
        authors: 'Qian, Cong, Yang et al.',
        year: 2023, venue: 'ACL 2024',
        description: 'ChatDev: a virtual software company of LLM agents with CEO, CTO, programmer, and tester roles collaborating to build software. Early digital workforce demonstration.',
        url: 'https://arxiv.org/abs/2307.07924',
        mustRead: false,
      },
      {
        title: 'The Rise and Potential of Large Language Model Based Agents: A Survey',
        authors: 'Xi, Chen, Guo et al.',
        year: 2023, venue: 'arXiv',
        description: 'Comprehensive 86-page survey covering single-agent and multi-agent architectures, applications in simulation, software development, and scientific research.',
        url: 'https://arxiv.org/abs/2309.07864',
        mustRead: false,
      },
    ],
    books: [
      {
        title: 'AI Agent Development with LangChain and LangGraph',
        authors: 'Tejaswi Kodali',
        year: 2024, level: 'Intermediate',
        description: 'Hands-on guide building production multi-agent systems with LangGraph, tool use, and state management. Covers the patterns used in enterprise AI digital worker deployments.',
        publisher: 'Packt Publishing',
      },
      {
        title: 'The Work of the Future: Building Better Jobs in an Age of Intelligent Machines',
        authors: 'David Autor, David Mindell, Elisabeth Reynolds',
        year: 2022, level: 'Beginner',
        description: 'MIT study on how AI and automation affect labor markets. Essential strategic reading for understanding the business context of AI digital workforce adoption.',
        publisher: 'MIT Press',
      },
    ],
    visual: [
      {
        title: 'Salesforce Agentforce Architecture Overview',
        creator: 'Salesforce',
        type: 'Article', year: 2024,
        description: 'Official architecture diagrams showing how Agentforce agents are defined, deployed, and governed within the Salesforce platform. Real-world enterprise AI worker architecture.',
        url: 'https://www.salesforce.com/agentforce/',
      },
      {
        title: 'Multi-AI Agent Systems with crewAI',
        creator: 'DeepLearning.AI',
        type: 'Video', year: 2024,
        description: 'Video course showing role-based agent teams in action. Visual walkthroughs of supervisor-worker patterns, task delegation, and inter-agent communication.',
        url: 'https://learn.deeplearning.ai',
      },
      {
        title: 'Microsoft AutoGen: Multi-Agent Conversation Explained',
        creator: 'Microsoft Research',
        type: 'Article', year: 2024,
        description: 'Architecture diagrams and walkthroughs of AutoGen conversation patterns: two-agent, group chat, nested chat, and hierarchical workforce patterns.',
        url: 'https://microsoft.github.io/autogen/',
      },
    ],
    code: [
      {
        name: 'crewAI',
        org: 'CrewAI Inc.',
        language: 'Python', stars: '28k+',
        description: 'The definitive role-based multi-agent framework. Agents, tasks, tools, crews, flows, and kickoffs. Best-in-class documentation and rapidly growing enterprise adoption.',
        url: 'https://github.com/crewAIInc/crewAI',
      },
      {
        name: 'autogen',
        org: 'Microsoft',
        language: 'Python', stars: '38k+',
        description: 'Multi-agent conversation framework with code execution. GroupChat for N-agent coordination, AssistantAgent and UserProxyAgent patterns for human-AI collaboration.',
        url: 'https://github.com/microsoft/autogen',
      },
      {
        name: 'AgentBench',
        org: 'THUDM (Tsinghua)',
        language: 'Python', stars: '2k+',
        description: 'Benchmark suite for evaluating LLM agents across OS, database, knowledge graph, digital card game, lateral thinking puzzle, and household task environments.',
        url: 'https://github.com/THUDM/AgentBench',
      },
      {
        name: 'ChatDev',
        org: 'OpenBMB',
        language: 'Python', stars: '26k+',
        description: 'Virtual software company built on LLM agents. CEO, CTO, programmer, tester agents collaborate to build software from a one-line specification. Early digital workforce proof-of-concept.',
        url: 'https://github.com/OpenBMB/ChatDev',
      },
    ],
    byYear: [
      {
        year: '2023',
        items: [
          { title: 'AutoGen — Multi-Agent Conversation Framework (Microsoft)', type: 'Paper', url: 'https://arxiv.org/abs/2308.08155' },
          { title: 'ChatDev — Virtual Software Company', type: 'Paper', url: 'https://arxiv.org/abs/2307.07924' },
          { title: 'AgentBench — Evaluating LLMs as Agents', type: 'Paper', url: 'https://arxiv.org/abs/2308.03688' },
        ],
      },
      {
        year: '2024',
        items: [
          { title: 'Salesforce Agentforce — enterprise AI worker platform', type: 'Product', url: 'https://www.salesforce.com/agentforce/' },
          { title: 'Microsoft Copilot Wave 2 — autonomous AI workers', type: 'Product', url: 'https://blogs.microsoft.com/blog/2024/09/16/microsoft-copilot-wave-2/' },
          { title: 'CrewAI Enterprise reaches Fortune 500', type: 'Milestone', url: 'https://www.crewai.com' },
        ],
      },
      {
        year: '2025',
        items: [
          { title: 'AI Digital Workforce governance frameworks standardized', type: 'Milestone', url: 'https://www.crewai.com' },
          { title: 'OpenAI Agents SDK released', type: 'Release', url: 'https://github.com/openai/openai-agents-python' },
          { title: 'ADW (AI Digital Workforce) platforms emerge', type: 'Milestone', url: '#' },
        ],
      },
    ],
  },

  6: {
    path: [
      {
        step: 1, level: 'Beginner', time: '2 hrs',
        title: 'Understand DAGs and Workflow Orchestration',
        description: 'Read the Temporal introduction and Apache Airflow concepts guide. Understanding DAG-based workflow orchestration is prerequisite to understanding GEE.',
        resource: 'docs.temporal.io · airflow.apache.org/docs',
        url: 'https://docs.temporal.io',
        type: 'guide',
      },
      {
        step: 2, level: 'Intermediate', time: '5 hrs',
        title: 'LangGraph: Agentic Workflows as State Machines',
        description: 'Complete the LangGraph Quickstart — build a workflow graph with conditional branches, parallel nodes, and checkpointing. LangGraph is the bridge between agents and GEE.',
        resource: 'langchain-ai.github.io/langgraph/tutorials/introduction',
        url: 'https://langchain-ai.github.io/langgraph/tutorials/introduction/',
        type: 'guide',
      },
      {
        step: 3, level: 'Intermediate', time: '6 hrs',
        title: 'Build an AI-Generated Workflow Pipeline',
        description: 'Implement a system that takes a business goal as input, uses an LLM to generate a workflow DAG (as JSON), validates it, then executes it via LangGraph. This is GEE in miniature.',
        resource: 'github.com/langchain-ai/langgraph/tree/main/examples',
        url: 'https://github.com/langchain-ai/langgraph/tree/main/examples',
        type: 'code',
      },
      {
        step: 4, level: 'Intermediate', time: '8 hrs',
        title: 'Temporal: Durable Execution for AI Workflows',
        description: 'Build a Temporal workflow that orchestrates AI agents. Understand activity retries, saga patterns, and exactly-once semantics — production requirements for AI-generated workflows.',
        resource: 'learn.temporal.io',
        url: 'https://learn.temporal.io',
        type: 'course',
      },
      {
        step: 5, level: 'Advanced', time: '6 hrs',
        title: 'Event-Driven AI Agents with Kafka',
        description: 'Implement an event-driven multi-agent system using Kafka. Workers subscribe to event topics; GEE publishes task assignments as messages. The enterprise-scale coordination pattern.',
        resource: 'developer.confluent.io/courses/kafka',
        url: 'https://developer.confluent.io/courses/apache-kafka/events/',
        type: 'course',
      },
      {
        step: 6, level: 'Advanced', time: '8 hrs',
        title: 'AI Workflow Governance and Safety',
        description: 'Implement pre-execution workflow validation: policy checking, risk scoring, and human approval gates. Read Anthropic\'s guide on agentic safety for production deployment context.',
        resource: 'docs.anthropic.com/en/docs/about-claude/models',
        url: 'https://docs.anthropic.com/en/docs/build-with-claude/agentic-and-long-running-tasks',
        type: 'guide',
      },
    ],
    papers: [
      {
        title: 'Executable Code Actions Elicit Better LLM Agents',
        authors: 'Wang, Chen, Yuan et al.',
        year: 2024, venue: 'ICML 2024',
        description: 'Shows that having LLMs generate executable Python code as actions (rather than JSON function calls) produces significantly better agent performance. Core to GEE\'s executable workflow generation.',
        url: 'https://arxiv.org/abs/2402.01030',
        mustRead: true,
      },
      {
        title: 'Natural Language to Code Generation in Interactive Data Science Notebooks',
        authors: 'Yin, Neubig, Yih, Riedel',
        year: 2022, venue: 'ACL 2022',
        description: 'Foundational work on translating natural language intent into executable code. Direct precursor to intent-to-workflow generation systems.',
        url: 'https://arxiv.org/abs/2302.00151',
        mustRead: false,
      },
      {
        title: 'TaskBench: Benchmarking Large Language Models for Task Automation',
        authors: 'Shen, Song, Tan et al.',
        year: 2023, venue: 'NeurIPS 2024',
        description: 'Evaluates LLMs on decomposing complex goals into executable task graphs. Directly measures the DAG generation capability central to GEE.',
        url: 'https://arxiv.org/abs/2311.18760',
        mustRead: false,
      },
      {
        title: 'HumanEval: Evaluating Large Language Models Trained on Code',
        authors: 'Chen, Tworek, Jun et al. (OpenAI)',
        year: 2021, venue: 'arXiv',
        description: 'The benchmark for code generation evaluation. Understanding how LLMs generate executable code is foundational to understanding how GEE generates executable workflows.',
        url: 'https://arxiv.org/abs/2107.03374',
        mustRead: false,
      },
    ],
    books: [
      {
        title: 'Fundamentals of Data Engineering',
        authors: 'Joe Reis, Matt Housley',
        year: 2022, level: 'Intermediate',
        description: 'Data pipeline orchestration concepts including DAGs, workflow engines, and event streaming. The engineering foundation required to build production GEE systems.',
        publisher: "O'Reilly Media",
      },
      {
        title: 'Kafka: The Definitive Guide (2nd ed.)',
        authors: 'Gwen Shapira, Todd Palino, Rajini Sivaram, Krit Petty',
        year: 2021, level: 'Intermediate',
        description: 'Complete guide to Apache Kafka for event-driven architecture. Essential for implementing event-driven AI agent coordination at enterprise scale.',
        publisher: "O'Reilly Media",
        url: 'https://www.confluent.io/resources/kafka-the-definitive-guide-v2/',
      },
    ],
    visual: [
      {
        title: 'LangGraph Conceptual Guide',
        creator: 'LangChain',
        type: 'Article', year: 2024,
        description: 'Visual diagrams of state graph execution, node functions, edge routing, and checkpointing. The primary reference for understanding agentic workflow architecture.',
        url: 'https://langchain-ai.github.io/langgraph/concepts/',
      },
      {
        title: 'Temporal Workflow Explained',
        creator: 'Temporal Technologies',
        type: 'Video', year: 2024,
        description: 'Visual explanation of durable execution — how Temporal makes workflows resilient to failures, retries, and crashes. Core reliability pattern for GEE.',
        url: 'https://www.youtube.com/@temporalio',
      },
      {
        title: 'Apache Kafka in 6 Minutes',
        creator: 'IBM Technology',
        type: 'Video', year: 2023,
        description: 'Concise visual introduction to Kafka topics, producers, consumers, and partitions. Best 6-minute primer before diving into event-driven agent coordination.',
        url: 'https://www.youtube.com/watch?v=Ch5VhJzaoaI',
      },
    ],
    code: [
      {
        name: 'langgraph',
        org: 'LangChain',
        language: 'Python', stars: '12k+',
        description: 'The production standard for agentic workflow graphs. State machines, parallel branches, human-in-the-loop nodes, and checkpointing. Foundation for GEE implementation.',
        url: 'https://github.com/langchain-ai/langgraph',
      },
      {
        name: 'temporal',
        org: 'Temporal Technologies',
        language: 'Go / Python / Java / TypeScript', stars: '12k+',
        description: 'Durable workflow execution engine. Exactly-once semantics, automatic retries, saga pattern support. The reliability layer for production AI-generated workflow execution.',
        url: 'https://github.com/temporalio/temporal',
      },
      {
        name: 'prefect',
        org: 'Prefect Technologies',
        language: 'Python', stars: '17k+',
        description: 'Modern dataflow orchestration with AI-native features. Dynamic task generation, automatic retries, observability. Production-friendly alternative to Airflow for GEE workloads.',
        url: 'https://github.com/PrefectHQ/prefect',
      },
      {
        name: 'dagster',
        org: 'Dagster Labs',
        language: 'Python', stars: '12k+',
        description: 'Data asset-aware orchestration. Software-defined assets, type-checked data flows, and rich observability. Well-suited for GEE workflows that produce data artifacts.',
        url: 'https://github.com/dagster-io/dagster',
      },
    ],
    byYear: [
      {
        year: '2023',
        items: [
          { title: 'TaskBench: LLMs for Task Automation', type: 'Paper', url: 'https://arxiv.org/abs/2311.18760' },
          { title: 'Executable Code Actions (CodeAct)', type: 'Paper', url: 'https://arxiv.org/abs/2402.01030' },
        ],
      },
      {
        year: '2024',
        items: [
          { title: 'LangGraph 0.2 — production multi-agent workflows', type: 'Release', url: 'https://github.com/langchain-ai/langgraph' },
          { title: 'Temporal + AI agent integration patterns emerge', type: 'Milestone', url: 'https://temporal.io' },
          { title: 'Prefect 3.0 — AI-native orchestration', type: 'Release', url: 'https://github.com/PrefectHQ/prefect' },
        ],
      },
      {
        year: '2025',
        items: [
          { title: 'GEE platforms reach enterprise production maturity', type: 'Milestone', url: '#' },
          { title: 'AI-generated workflows exceed manual workflows at early adopters', type: 'Milestone', url: '#' },
          { title: 'Workflow generation benchmarks published', type: 'Milestone', url: '#' },
        ],
      },
    ],
  },

  7: {
    path: [
      {
        step: 1, level: 'Beginner', time: '3 hrs',
        title: 'Read the Enterprise AI-EOS Vision Papers',
        description: 'Read Anthropic\'s research on multi-agent systems and OpenAI\'s operator framework documentation. Understand what enterprise AI coordination at scale looks like today.',
        resource: 'docs.anthropic.com · platform.openai.com/docs',
        url: 'https://docs.anthropic.com/en/docs/build-with-claude/agentic-and-long-running-tasks',
        type: 'article',
      },
      {
        step: 2, level: 'Intermediate', time: '8 hrs',
        title: 'Build a Full Agentic Platform (LangGraph + MCP)',
        description: 'Combine LangGraph for workflow orchestration, MCP for tool connectivity, and an LLM judge for output validation. This is the minimal AI-EOS architecture at prototype scale.',
        resource: 'langchain-ai.github.io/langgraph · modelcontextprotocol.io',
        url: 'https://langchain-ai.github.io/langgraph/',
        type: 'guide',
      },
      {
        step: 3, level: 'Intermediate', time: '10 hrs',
        title: 'Enterprise AI Governance Frameworks',
        description: 'Study NIST AI RMF, ISO 42001, and the EU AI Act. Understanding the regulatory requirements is prerequisite to designing compliant AI-EOS architecture.',
        resource: 'nist.gov/system/files/documents/2023/01/26/AI RMF 1.0.pdf',
        url: 'https://www.nist.gov/artificial-intelligence/ai-risk-management-framework',
        type: 'guide',
      },
      {
        step: 4, level: 'Advanced', time: '12 hrs',
        title: 'Study Production AI Platform Architecture',
        description: 'Read case studies from Andreessen Horowitz, Sequoia, and McKinsey on enterprise AI platform architecture. Follow ML engineers at Uber, Airbnb, Netflix on their AI infrastructure blogs.',
        resource: 'a16z.com/ai · mckinsey.com/capabilities/quantumblack',
        url: 'https://a16z.com/ai/',
        type: 'article',
      },
      {
        step: 5, level: 'Advanced', time: '10 hrs',
        title: 'Vector Databases and Enterprise Memory Architecture',
        description: 'Build enterprise memory systems with Pinecone or Weaviate. Implement different memory types — working, episodic, semantic — as distinct namespaces with governance controls.',
        resource: 'docs.pinecone.io · weaviate.io/developers/weaviate',
        url: 'https://docs.pinecone.io',
        type: 'guide',
      },
      {
        step: 6, level: 'Advanced', time: '15 hrs',
        title: 'Design an AI-EOS Architecture for an Enterprise Domain',
        description: 'Select a domain (finance, supply chain, customer ops) and design a full AI-EOS stack: intent layer, agent registry, memory fabric, workflow engine, governance layer, observability. Document the architecture.',
        resource: 'Use the AI Evolution EA artifacts as reference',
        url: '#',
        type: 'project',
      },
    ],
    papers: [
      {
        title: 'Practices for Governing Agentic AI Systems',
        authors: 'Anthropic Policy Team',
        year: 2024, venue: 'Anthropic',
        description: 'Framework for governing agentic AI deployments — minimal footprint principle, authorization boundaries, oversight mechanisms. The practical governance foundation for AI-EOS.',
        url: 'https://www.anthropic.com/research/agentic-ai-systems-governance',
        mustRead: true,
      },
      {
        title: 'NIST AI Risk Management Framework (AI RMF 1.0)',
        authors: 'National Institute of Standards and Technology',
        year: 2023, venue: 'NIST',
        description: 'The US government\'s framework for managing AI risks — Govern, Map, Measure, Manage. The foundational reference for enterprise AI governance and AI-EOS compliance design.',
        url: 'https://doi.org/10.6028/NIST.AI.100-1',
        mustRead: true,
      },
      {
        title: 'Holistic Evaluation of Language Models (HELM)',
        authors: 'Liang, Bommasani, Lee et al. (Stanford)',
        year: 2022, venue: 'TMLR 2023',
        description: 'Comprehensive benchmark evaluating LLMs across accuracy, calibration, robustness, fairness, bias, toxicity, and efficiency. Framework for AI-EOS model evaluation requirements.',
        url: 'https://arxiv.org/abs/2211.09110',
        mustRead: false,
      },
      {
        title: 'Constitutional AI: A Framework for Machine Ethics',
        authors: 'Bai, Jones et al. (Anthropic)',
        year: 2022, venue: 'Anthropic',
        description: 'Constitutional AI as a self-governing mechanism. AI systems that enforce their own ethical rules — the embryonic form of the "cognitive constitutions" that AI-EOS requires.',
        url: 'https://arxiv.org/abs/2212.08073',
        mustRead: false,
      },
      {
        title: 'The EU Artificial Intelligence Act',
        authors: 'European Parliament',
        year: 2024, venue: 'Official Journal of the EU',
        description: 'The world\'s first comprehensive AI regulatory framework. Mandatory reading for designing AI-EOS in any organization operating in or serving European markets.',
        url: 'https://artificialintelligenceact.eu/',
        mustRead: false,
      },
    ],
    books: [
      {
        title: 'AI Strategy: A Practitioner\'s Guide',
        authors: 'Ajay Agrawal, Joshua Gans, Avi Goldfarb',
        year: 2022, level: 'Beginner',
        description: 'Economic framework for AI strategy decisions — prediction machines, judgment, and the organizational design implications of AI. Strategic foundation for AI-EOS adoption.',
        publisher: 'Harvard Business Review Press',
      },
      {
        title: 'The Technology Fallacy',
        authors: 'Gerald Kane et al. (MIT Sloan)',
        year: 2019, level: 'Beginner',
        description: 'MIT research on digital transformation — the organizational and cultural changes required to benefit from transformative technology. Applies directly to AI-EOS adoption.',
        publisher: 'MIT Press',
      },
      {
        title: 'Prediction Machines: The Simple Economics of Artificial Intelligence',
        authors: 'Ajay Agrawal, Joshua Gans, Avi Goldfarb',
        year: 2018, level: 'Beginner',
        description: 'Frames AI as a "prediction machine" that reduces the cost of prediction. The economic lens for understanding AI-EOS value creation at enterprise scale.',
        publisher: 'Harvard Business Review Press',
      },
      {
        title: 'Co-Intelligence: Living and Working with AI',
        authors: 'Ethan Mollick',
        year: 2024, level: 'Beginner',
        description: 'Wharton professor on the practical and strategic implications of working alongside AI. Essential framing for the human-AI collaboration model at the heart of AI-EOS.',
        publisher: 'Portfolio / Penguin',
      },
    ],
    visual: [
      {
        title: 'NVIDIA AI Blueprint: Enterprise AI Architecture',
        creator: 'NVIDIA',
        type: 'Article', year: 2024,
        description: 'NVIDIA\'s reference architecture for enterprise AI deployment — NIM microservices, Nemo guardrails, and the full AI-EOS technology stack from a hardware-software perspective.',
        url: 'https://www.nvidia.com/en-us/ai/',
      },
      {
        title: 'The State of AI Report 2024',
        creator: 'Nathan Benaich, Air Street Capital',
        type: 'Article', year: 2024,
        description: 'Annual report covering frontier AI research, industry trends, and enterprise adoption. Best year-in-review resource for tracking the AI-EOS era as it develops.',
        url: 'https://www.stateof.ai/',
      },
      {
        title: 'The Future of Enterprise AI (a16z)',
        creator: 'Andreessen Horowitz',
        type: 'Article', year: 2024,
        description: 'a16z\'s thesis on enterprise AI architecture evolution — from single models to AI-native enterprises. Strategic framing closely aligned with the AI-EOS vision.',
        url: 'https://a16z.com/ai/',
      },
      {
        title: 'EU AI Act: A Visual Guide',
        creator: 'Future of Life Institute',
        type: 'Interactive', year: 2024,
        description: 'Interactive guide to the EU AI Act\'s risk classifications, obligations, and compliance requirements. Essential reference for AI-EOS compliance design.',
        url: 'https://artificialintelligenceact.eu/assessment/eu-ai-act-compliance-checker/',
      },
    ],
    code: [
      {
        name: 'langgraph',
        org: 'LangChain',
        language: 'Python', stars: '12k+',
        description: 'The current leading AI orchestration framework. Today\'s LangGraph is what AI-EOS workflow engines will evolve from — start here for production agentic platform architecture.',
        url: 'https://github.com/langchain-ai/langgraph',
      },
      {
        name: 'weaviate',
        org: 'Weaviate',
        language: 'Go / Python', stars: '12k+',
        description: 'AI-native vector database for enterprise memory. Multi-tenancy, hybrid search, GraphQL API. Foundation for the AI Memory Factory in AI-EOS architecture.',
        url: 'https://github.com/weaviate/weaviate',
      },
      {
        name: 'NeMo-Guardrails',
        org: 'NVIDIA',
        language: 'Python', stars: '4k+',
        description: 'Programmable guardrails for LLM-based applications — the safety and compliance enforcement layer. Core component of production AI-EOS governance.',
        url: 'https://github.com/NVIDIA/NeMo-Guardrails',
      },
      {
        name: 'opentelemetry-python',
        org: 'OpenTelemetry',
        language: 'Python', stars: '2k+',
        description: 'Observability instrumentation for AI systems. Traces, metrics, and logs across the full AI-EOS stack. Production-grade observability for governed AI operations.',
        url: 'https://github.com/open-telemetry/opentelemetry-python',
      },
      {
        name: 'open-policy-agent (OPA)',
        org: 'CNCF',
        language: 'Go / Rego', stars: '10k+',
        description: 'The standard policy-as-code engine. OPA powers the Cognitive Policy Engine in ECG — use it to implement runtime policy enforcement for AI-EOS governance.',
        url: 'https://github.com/open-policy-agent/opa',
      },
    ],
    byYear: [
      {
        year: '2024',
        items: [
          { title: 'NIST AI RMF 1.0 — enterprise AI governance standard', type: 'Standard', url: 'https://www.nist.gov/artificial-intelligence/ai-risk-management-framework' },
          { title: 'EU AI Act enters into force (Aug 2024)', type: 'Regulation', url: 'https://artificialintelligenceact.eu/' },
          { title: 'MCP — universal AI tool connectivity standard', type: 'Standard', url: 'https://modelcontextprotocol.io' },
          { title: 'ISO/IEC 42001 — AI Management System Standard', type: 'Standard', url: 'https://www.iso.org/standard/81230.html' },
        ],
      },
      {
        year: '2025',
        items: [
          { title: 'OpenAI Agents SDK — enterprise agent platform', type: 'Release', url: 'https://github.com/openai/openai-agents-python' },
          { title: 'First AI-EOS deployments in technology enterprises', type: 'Milestone', url: '#' },
          { title: 'NVIDIA NIM enterprise microservices GA', type: 'Release', url: 'https://www.nvidia.com/en-us/ai/nim/' },
        ],
      },
      {
        year: '2026–2030+',
        items: [
          { title: 'AI-EOS becomes standard enterprise architecture', type: 'Prediction', url: '#' },
          { title: 'Self-governing AI enterprises reach frontier orgs', type: 'Prediction', url: '#' },
          { title: 'AI-native enterprises operate without legacy stacks', type: 'Prediction', url: '#' },
        ],
      },
    ],
  },
}
